-- DO NOT MODIFY THIS FILE.
-- This file is generated by hard_tests_gen

package tlbinvf_test_const is
    -- The simulator handle a too large memory space
    constant MAX_RAM_ADDRESS: integer := 1024 - 1;

    constant CLK_PERIOD: time := 10 ns;
end tlbinvf_test_const;
