#Clock
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports clk_in]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD LVCMOS33} [get_ports clk_uart_in]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_uart_in_IBUF]

# 50MHz main clock in
create_clock -period 20.000 -name clk_in -waveform {0.000 10.000} [get_ports clk_in]
# 11.0592MHz clock for UART
create_clock -period 90.422 -name clk_uart_in -waveform {0.000 45.211} [get_ports clk_uart_in]
# 25MHz derived clock
# Code below may bring warnings in synthesis stage and it doesn't matter
# It's only needed in implementation stage
create_generated_clock -name clk25 -source [get_pins -hierarchical *mmcm_adv_inst/CLKIN1] -master_clock clk_in [get_pins -hierarchical *mmcm_adv_inst/CLKOUT0]

#Touch Button
set_property IOSTANDARD LVCMOS33 [get_ports {touch_btn[*]}]
set_property PACKAGE_PIN J19 [get_ports {touch_btn[0]}]
set_property PACKAGE_PIN E25 [get_ports {touch_btn[1]}]
set_property PACKAGE_PIN F23 [get_ports {touch_btn[2]}]
set_property PACKAGE_PIN E23 [get_ports {touch_btn[3]}]
set_property PACKAGE_PIN H19 [get_ports {touch_btn[4]}]
set_property PACKAGE_PIN F22 [get_ports {touch_btn[5]}]

#required if touch_btn[4] used as manual clock source
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets touch_btn_IBUF[4]]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {touch_btn_IBUF[5]}]

#CPLD
set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVCMOS33} [get_ports uart_wrn]
set_property -dict {PACKAGE_PIN K22 IOSTANDARD LVCMOS33} [get_ports uart_rdn]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS33} [get_ports uart_tbre]
set_property -dict {PACKAGE_PIN M16 IOSTANDARD LVCMOS33} [get_ports uart_tsre]
set_property -dict {PACKAGE_PIN J24 IOSTANDARD LVCMOS33} [get_ports uart_dataready]

#Ext serial
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN L19} [get_ports txd]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN K21} [get_ports rxd]

#USB
set_property -dict {PACKAGE_PIN K3 IOSTANDARD LVCMOS33} [get_ports sl811_a0]
set_property -dict {PACKAGE_PIN M1 IOSTANDARD LVCMOS33} [get_ports sl811_we_n]
set_property -dict {PACKAGE_PIN J3 IOSTANDARD LVCMOS33} [get_ports sl811_rd_n]
set_property -dict {PACKAGE_PIN K1 IOSTANDARD LVCMOS33} [get_ports sl811_cs_n]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD LVCMOS33} [get_ports sl811_rst_n]
set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVCMOS33} [get_ports sl811_drq]
set_property -dict {PACKAGE_PIN H3 IOSTANDARD LVCMOS33} [get_ports sl811_dack]
set_property -dict {PACKAGE_PIN M4 IOSTANDARD LVCMOS33} [get_ports sl811_int]
set_property -dict {PACKAGE_PIN L8 IOSTANDARD LVCMOS33} [get_ports {sl811_data[0]}]
set_property -dict {PACKAGE_PIN M6 IOSTANDARD LVCMOS33} [get_ports {sl811_data[1]}]
set_property -dict {PACKAGE_PIN L5 IOSTANDARD LVCMOS33} [get_ports {sl811_data[2]}]
set_property -dict {PACKAGE_PIN L7 IOSTANDARD LVCMOS33} [get_ports {sl811_data[3]}]
set_property -dict {PACKAGE_PIN L4 IOSTANDARD LVCMOS33} [get_ports {sl811_data[4]}]
set_property -dict {PACKAGE_PIN L3 IOSTANDARD LVCMOS33} [get_ports {sl811_data[5]}]
set_property -dict {PACKAGE_PIN L2 IOSTANDARD LVCMOS33} [get_ports {sl811_data[6]}]
set_property -dict {PACKAGE_PIN R7 IOSTANDARD LVCMOS33} [get_ports {sl811_data[7]}]

#Ethernet
set_property -dict {PACKAGE_PIN D4 IOSTANDARD LVCMOS33} [get_ports dm9k_we_n]
set_property -dict {PACKAGE_PIN D3 IOSTANDARD LVCMOS33} [get_ports dm9k_rd_n]
set_property -dict {PACKAGE_PIN C3 IOSTANDARD LVCMOS33} [get_ports dm9k_cs_n]
set_property -dict {PACKAGE_PIN C4 IOSTANDARD LVCMOS33} [get_ports dm9k_rst_n]
set_property -dict {PACKAGE_PIN H8 IOSTANDARD LVCMOS33} [get_ports dm9k_int]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports dm9k_cmd]
set_property -dict {PACKAGE_PIN G1 IOSTANDARD LVCMOS33} [get_ports {dm9k_data[0]}]
set_property -dict {PACKAGE_PIN H2 IOSTANDARD LVCMOS33} [get_ports {dm9k_data[1]}]
set_property -dict {PACKAGE_PIN J1 IOSTANDARD LVCMOS33} [get_ports {dm9k_data[2]}]
set_property -dict {PACKAGE_PIN H7 IOSTANDARD LVCMOS33} [get_ports {dm9k_data[3]}]
set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVCMOS33} [get_ports {dm9k_data[4]}]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports {dm9k_data[5]}]
set_property -dict {PACKAGE_PIN K7 IOSTANDARD LVCMOS33} [get_ports {dm9k_data[6]}]
set_property -dict {PACKAGE_PIN K6 IOSTANDARD LVCMOS33} [get_ports {dm9k_data[7]}]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD LVCMOS33} [get_ports {dm9k_data[8]}]
set_property -dict {PACKAGE_PIN H6 IOSTANDARD LVCMOS33} [get_ports {dm9k_data[9]}]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVCMOS33} [get_ports {dm9k_data[10]}]
set_property -dict {PACKAGE_PIN H1 IOSTANDARD LVCMOS33} [get_ports {dm9k_data[11]}]
set_property -dict {PACKAGE_PIN J5 IOSTANDARD LVCMOS33} [get_ports {dm9k_data[12]}]
set_property -dict {PACKAGE_PIN J6 IOSTANDARD LVCMOS33} [get_ports {dm9k_data[13]}]
set_property -dict {PACKAGE_PIN K5 IOSTANDARD LVCMOS33} [get_ports {dm9k_data[14]}]
set_property -dict {PACKAGE_PIN F5 IOSTANDARD LVCMOS33} [get_ports {dm9k_data[15]}]

#Digital Video
set_property -dict {PACKAGE_PIN J21 IOSTANDARD LVCMOS33} [get_ports video_clk]
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33} [get_ports {video_pixel[7]}]
set_property -dict {PACKAGE_PIN N21 IOSTANDARD LVCMOS33} [get_ports {video_pixel[6]}]
set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVCMOS33} [get_ports {video_pixel[5]}]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports {video_pixel[4]}]
set_property -dict {PACKAGE_PIN G20 IOSTANDARD LVCMOS33} [get_ports {video_pixel[3]}]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports {video_pixel[2]}]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports {video_pixel[1]}]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports {video_pixel[0]}]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33} [get_ports video_hsync]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports video_vsync]
set_property -dict {PACKAGE_PIN J20 IOSTANDARD LVCMOS33} [get_ports video_de]

#LEDS
set_property IOSTANDARD LVCMOS33 [get_ports {leds[*]}]
set_property PACKAGE_PIN A17 [get_ports {leds[0]}]
set_property PACKAGE_PIN G16 [get_ports {leds[1]}]
set_property PACKAGE_PIN E16 [get_ports {leds[2]}]
set_property PACKAGE_PIN H17 [get_ports {leds[3]}]
set_property PACKAGE_PIN G17 [get_ports {leds[4]}]
set_property PACKAGE_PIN F18 [get_ports {leds[5]}]
set_property PACKAGE_PIN F19 [get_ports {leds[6]}]
set_property PACKAGE_PIN F20 [get_ports {leds[7]}]
set_property PACKAGE_PIN C17 [get_ports {leds[8]}]
set_property PACKAGE_PIN F17 [get_ports {leds[9]}]
set_property PACKAGE_PIN B17 [get_ports {leds[10]}]
set_property PACKAGE_PIN D19 [get_ports {leds[11]}]
set_property PACKAGE_PIN A18 [get_ports {leds[12]}]
set_property PACKAGE_PIN A19 [get_ports {leds[13]}]
set_property PACKAGE_PIN E17 [get_ports {leds[14]}]
set_property PACKAGE_PIN E18 [get_ports {leds[15]}]

#DPY0
set_property PACKAGE_PIN D16 [get_ports {leds[16]}]
set_property PACKAGE_PIN F15 [get_ports {leds[17]}]
set_property PACKAGE_PIN H15 [get_ports {leds[18]}]
set_property PACKAGE_PIN G15 [get_ports {leds[19]}]
set_property PACKAGE_PIN H16 [get_ports {leds[20]}]
set_property PACKAGE_PIN H14 [get_ports {leds[21]}]
set_property PACKAGE_PIN G19 [get_ports {leds[22]}]
set_property PACKAGE_PIN J8 [get_ports {leds[23]}]

#DPY2
set_property PACKAGE_PIN H9 [get_ports {leds[24]}]
set_property PACKAGE_PIN G8 [get_ports {leds[25]}]
set_property PACKAGE_PIN G7 [get_ports {leds[26]}]
set_property PACKAGE_PIN G6 [get_ports {leds[27]}]
set_property PACKAGE_PIN D6 [get_ports {leds[28]}]
set_property PACKAGE_PIN E5 [get_ports {leds[29]}]
set_property PACKAGE_PIN F4 [get_ports {leds[30]}]
set_property PACKAGE_PIN G5 [get_ports {leds[31]}]

#DIP_SW
set_property IOSTANDARD LVCMOS33 [get_ports {dip_sw[*]}]
set_property PACKAGE_PIN N3 [get_ports {dip_sw[0]}]
set_property PACKAGE_PIN N4 [get_ports {dip_sw[1]}]
set_property PACKAGE_PIN P3 [get_ports {dip_sw[2]}]
set_property PACKAGE_PIN P4 [get_ports {dip_sw[3]}]
set_property PACKAGE_PIN R5 [get_ports {dip_sw[4]}]
set_property PACKAGE_PIN T7 [get_ports {dip_sw[5]}]
set_property PACKAGE_PIN R8 [get_ports {dip_sw[6]}]
set_property PACKAGE_PIN T8 [get_ports {dip_sw[7]}]
set_property PACKAGE_PIN N2 [get_ports {dip_sw[8]}]
set_property PACKAGE_PIN N1 [get_ports {dip_sw[9]}]
set_property PACKAGE_PIN P1 [get_ports {dip_sw[10]}]
set_property PACKAGE_PIN R2 [get_ports {dip_sw[11]}]
set_property PACKAGE_PIN R1 [get_ports {dip_sw[12]}]
set_property PACKAGE_PIN T2 [get_ports {dip_sw[13]}]
set_property PACKAGE_PIN U1 [get_ports {dip_sw[14]}]
set_property PACKAGE_PIN U2 [get_ports {dip_sw[15]}]
set_property PACKAGE_PIN U6 [get_ports {dip_sw[16]}]
set_property PACKAGE_PIN R6 [get_ports {dip_sw[17]}]
set_property PACKAGE_PIN U5 [get_ports {dip_sw[18]}]
set_property PACKAGE_PIN T5 [get_ports {dip_sw[19]}]
set_property PACKAGE_PIN U4 [get_ports {dip_sw[20]}]
set_property PACKAGE_PIN T4 [get_ports {dip_sw[21]}]
set_property PACKAGE_PIN T3 [get_ports {dip_sw[22]}]
set_property PACKAGE_PIN R3 [get_ports {dip_sw[23]}]
set_property PACKAGE_PIN P5 [get_ports {dip_sw[24]}]
set_property PACKAGE_PIN P6 [get_ports {dip_sw[25]}]
set_property PACKAGE_PIN P8 [get_ports {dip_sw[26]}]
set_property PACKAGE_PIN N8 [get_ports {dip_sw[27]}]
set_property PACKAGE_PIN N6 [get_ports {dip_sw[28]}]
set_property PACKAGE_PIN N7 [get_ports {dip_sw[29]}]
set_property PACKAGE_PIN M7 [get_ports {dip_sw[30]}]
set_property PACKAGE_PIN M5 [get_ports {dip_sw[31]}]

set_property IOSTANDARD LVCMOS33 [get_ports {flash_a[*]}]
set_property PACKAGE_PIN K8 [get_ports {flash_a[0]}]
set_property PACKAGE_PIN C26 [get_ports {flash_a[1]}]
set_property PACKAGE_PIN B26 [get_ports {flash_a[2]}]
set_property PACKAGE_PIN B25 [get_ports {flash_a[3]}]
set_property PACKAGE_PIN A25 [get_ports {flash_a[4]}]
set_property PACKAGE_PIN D24 [get_ports {flash_a[5]}]
set_property PACKAGE_PIN C24 [get_ports {flash_a[6]}]
set_property PACKAGE_PIN B24 [get_ports {flash_a[7]}]
set_property PACKAGE_PIN A24 [get_ports {flash_a[8]}]
set_property PACKAGE_PIN C23 [get_ports {flash_a[9]}]
set_property PACKAGE_PIN D23 [get_ports {flash_a[10]}]
set_property PACKAGE_PIN A23 [get_ports {flash_a[11]}]
set_property PACKAGE_PIN C21 [get_ports {flash_a[12]}]
set_property PACKAGE_PIN B21 [get_ports {flash_a[13]}]
set_property PACKAGE_PIN E22 [get_ports {flash_a[14]}]
set_property PACKAGE_PIN E21 [get_ports {flash_a[15]}]
set_property PACKAGE_PIN E20 [get_ports {flash_a[16]}]
set_property PACKAGE_PIN D21 [get_ports {flash_a[17]}]
set_property PACKAGE_PIN B20 [get_ports {flash_a[18]}]
set_property PACKAGE_PIN D20 [get_ports {flash_a[19]}]
set_property PACKAGE_PIN B19 [get_ports {flash_a[20]}]
set_property PACKAGE_PIN C19 [get_ports {flash_a[21]}]
set_property PACKAGE_PIN A20 [get_ports {flash_a[22]}]

set_property IOSTANDARD LVCMOS33 [get_ports {flash_data[*]}]
set_property PACKAGE_PIN F8 [get_ports {flash_data[0]}]
set_property PACKAGE_PIN E6 [get_ports {flash_data[1]}]
set_property PACKAGE_PIN B5 [get_ports {flash_data[2]}]
set_property PACKAGE_PIN A4 [get_ports {flash_data[3]}]
set_property PACKAGE_PIN A3 [get_ports {flash_data[4]}]
set_property PACKAGE_PIN B2 [get_ports {flash_data[5]}]
set_property PACKAGE_PIN C2 [get_ports {flash_data[6]}]
set_property PACKAGE_PIN F2 [get_ports {flash_data[7]}]
set_property PACKAGE_PIN F7 [get_ports {flash_data[8]}]
set_property PACKAGE_PIN A5 [get_ports {flash_data[9]}]
set_property PACKAGE_PIN D5 [get_ports {flash_data[10]}]
set_property PACKAGE_PIN B4 [get_ports {flash_data[11]}]
set_property PACKAGE_PIN A2 [get_ports {flash_data[12]}]
set_property PACKAGE_PIN B1 [get_ports {flash_data[13]}]
set_property PACKAGE_PIN G2 [get_ports {flash_data[14]}]
set_property PACKAGE_PIN E1 [get_ports {flash_data[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports flash_byte_n]
set_property PACKAGE_PIN G9 [get_ports flash_byte_n]
set_property IOSTANDARD LVCMOS33 [get_ports flash_ce_n]
set_property PACKAGE_PIN A22 [get_ports flash_ce_n]
set_property IOSTANDARD LVCMOS33 [get_ports flash_oe_n]
set_property PACKAGE_PIN D1 [get_ports flash_oe_n]
set_property IOSTANDARD LVCMOS33 [get_ports flash_rp_n]
set_property PACKAGE_PIN C22 [get_ports flash_rp_n]
set_property IOSTANDARD LVCMOS33 [get_ports flash_vpen]
set_property PACKAGE_PIN B22 [get_ports flash_vpen]
set_property IOSTANDARD LVCMOS33 [get_ports flash_we_n]
set_property PACKAGE_PIN C1 [get_ports flash_we_n]

# If we want to use constraint to implement the holding time for writing,
# we can set `addr` and `data` to hold for 11ns (-min -11), and set `we` to
# setup within 10ns (-max 30, i.e. (clk25 period) 40ns - 10ns = 30ns)
# However, this method is too time-consuming in the implementation stage,
# so we are still using `and clk` method in `sram_ctrl`
set_property IOSTANDARD LVCMOS33 [get_ports {base_ram_addr[*]}]
set_property PACKAGE_PIN F24 [get_ports {base_ram_addr[0]}]
set_property PACKAGE_PIN G24 [get_ports {base_ram_addr[1]}]
set_property PACKAGE_PIN L24 [get_ports {base_ram_addr[2]}]
set_property PACKAGE_PIN L23 [get_ports {base_ram_addr[3]}]
set_property PACKAGE_PIN N16 [get_ports {base_ram_addr[4]}]
set_property PACKAGE_PIN G21 [get_ports {base_ram_addr[5]}]
set_property PACKAGE_PIN K17 [get_ports {base_ram_addr[6]}]
set_property PACKAGE_PIN L17 [get_ports {base_ram_addr[7]}]
set_property PACKAGE_PIN J15 [get_ports {base_ram_addr[8]}]
set_property PACKAGE_PIN H23 [get_ports {base_ram_addr[9]}]
set_property PACKAGE_PIN P14 [get_ports {base_ram_addr[10]}]
set_property PACKAGE_PIN L14 [get_ports {base_ram_addr[11]}]
set_property PACKAGE_PIN L15 [get_ports {base_ram_addr[12]}]
set_property PACKAGE_PIN K15 [get_ports {base_ram_addr[13]}]
set_property PACKAGE_PIN J14 [get_ports {base_ram_addr[14]}]
set_property PACKAGE_PIN M24 [get_ports {base_ram_addr[15]}]
set_property PACKAGE_PIN N17 [get_ports {base_ram_addr[16]}]
set_property PACKAGE_PIN N23 [get_ports {base_ram_addr[17]}]
set_property PACKAGE_PIN N24 [get_ports {base_ram_addr[18]}]
set_property PACKAGE_PIN P23 [get_ports {base_ram_addr[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {base_ram_be_n[*]}]
set_property PACKAGE_PIN M26 [get_ports {base_ram_be_n[0]}]
set_property PACKAGE_PIN L25 [get_ports {base_ram_be_n[1]}]
set_property PACKAGE_PIN D26 [get_ports {base_ram_be_n[2]}]
set_property PACKAGE_PIN D25 [get_ports {base_ram_be_n[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {base_ram_data[*]}]
set_property PACKAGE_PIN M22 [get_ports {base_ram_data[0]}]
set_property PACKAGE_PIN N14 [get_ports {base_ram_data[1]}]
set_property PACKAGE_PIN N22 [get_ports {base_ram_data[2]}]
set_property PACKAGE_PIN R20 [get_ports {base_ram_data[3]}]
set_property PACKAGE_PIN M25 [get_ports {base_ram_data[4]}]
set_property PACKAGE_PIN N26 [get_ports {base_ram_data[5]}]
set_property PACKAGE_PIN P26 [get_ports {base_ram_data[6]}]
set_property PACKAGE_PIN P25 [get_ports {base_ram_data[7]}]
set_property PACKAGE_PIN J23 [get_ports {base_ram_data[8]}]
set_property PACKAGE_PIN J18 [get_ports {base_ram_data[9]}]
set_property PACKAGE_PIN E26 [get_ports {base_ram_data[10]}]
set_property PACKAGE_PIN H21 [get_ports {base_ram_data[11]}]
set_property PACKAGE_PIN H22 [get_ports {base_ram_data[12]}]
set_property PACKAGE_PIN H18 [get_ports {base_ram_data[13]}]
set_property PACKAGE_PIN G22 [get_ports {base_ram_data[14]}]
set_property PACKAGE_PIN J16 [get_ports {base_ram_data[15]}]
set_property PACKAGE_PIN N19 [get_ports {base_ram_data[16]}]
set_property PACKAGE_PIN P18 [get_ports {base_ram_data[17]}]
set_property PACKAGE_PIN P19 [get_ports {base_ram_data[18]}]
set_property PACKAGE_PIN R18 [get_ports {base_ram_data[19]}]
set_property PACKAGE_PIN K20 [get_ports {base_ram_data[20]}]
set_property PACKAGE_PIN M19 [get_ports {base_ram_data[21]}]
set_property PACKAGE_PIN L22 [get_ports {base_ram_data[22]}]
set_property PACKAGE_PIN M21 [get_ports {base_ram_data[23]}]
set_property PACKAGE_PIN K26 [get_ports {base_ram_data[24]}]
set_property PACKAGE_PIN K25 [get_ports {base_ram_data[25]}]
set_property PACKAGE_PIN J26 [get_ports {base_ram_data[26]}]
set_property PACKAGE_PIN J25 [get_ports {base_ram_data[27]}]
set_property PACKAGE_PIN H26 [get_ports {base_ram_data[28]}]
set_property PACKAGE_PIN G26 [get_ports {base_ram_data[29]}]
set_property PACKAGE_PIN G25 [get_ports {base_ram_data[30]}]
set_property PACKAGE_PIN F25 [get_ports {base_ram_data[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports base_ram_ce_n]
set_property PACKAGE_PIN K18 [get_ports base_ram_ce_n]
set_property IOSTANDARD LVCMOS33 [get_ports base_ram_oe_n]
set_property PACKAGE_PIN K16 [get_ports base_ram_oe_n]
set_property IOSTANDARD LVCMOS33 [get_ports base_ram_we_n]
set_property PACKAGE_PIN P24 [get_ports base_ram_we_n]

set_property IOSTANDARD LVCMOS33 [get_ports {ext_ram_addr[*]}]
set_property PACKAGE_PIN Y21 [get_ports {ext_ram_addr[0]}]
set_property PACKAGE_PIN Y26 [get_ports {ext_ram_addr[1]}]
set_property PACKAGE_PIN AA25 [get_ports {ext_ram_addr[2]}]
set_property PACKAGE_PIN Y22 [get_ports {ext_ram_addr[3]}]
set_property PACKAGE_PIN Y23 [get_ports {ext_ram_addr[4]}]
set_property PACKAGE_PIN T18 [get_ports {ext_ram_addr[5]}]
set_property PACKAGE_PIN T23 [get_ports {ext_ram_addr[6]}]
set_property PACKAGE_PIN T24 [get_ports {ext_ram_addr[7]}]
set_property PACKAGE_PIN U19 [get_ports {ext_ram_addr[8]}]
set_property PACKAGE_PIN V24 [get_ports {ext_ram_addr[9]}]
set_property PACKAGE_PIN W26 [get_ports {ext_ram_addr[10]}]
set_property PACKAGE_PIN W24 [get_ports {ext_ram_addr[11]}]
set_property PACKAGE_PIN Y25 [get_ports {ext_ram_addr[12]}]
set_property PACKAGE_PIN W23 [get_ports {ext_ram_addr[13]}]
set_property PACKAGE_PIN W21 [get_ports {ext_ram_addr[14]}]
set_property PACKAGE_PIN V14 [get_ports {ext_ram_addr[15]}]
set_property PACKAGE_PIN U14 [get_ports {ext_ram_addr[16]}]
set_property PACKAGE_PIN T14 [get_ports {ext_ram_addr[17]}]
set_property PACKAGE_PIN U15 [get_ports {ext_ram_addr[18]}]
set_property PACKAGE_PIN T15 [get_ports {ext_ram_addr[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ext_ram_be_n[*]}]
set_property PACKAGE_PIN U26 [get_ports {ext_ram_be_n[0]}]
set_property PACKAGE_PIN T25 [get_ports {ext_ram_be_n[1]}]
set_property PACKAGE_PIN R17 [get_ports {ext_ram_be_n[2]}]
set_property PACKAGE_PIN R21 [get_ports {ext_ram_be_n[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ext_ram_data[*]}]
set_property PACKAGE_PIN W20 [get_ports {ext_ram_data[0]}]
set_property PACKAGE_PIN W19 [get_ports {ext_ram_data[1]}]
set_property PACKAGE_PIN V19 [get_ports {ext_ram_data[2]}]
set_property PACKAGE_PIN W18 [get_ports {ext_ram_data[3]}]
set_property PACKAGE_PIN V18 [get_ports {ext_ram_data[4]}]
set_property PACKAGE_PIN T17 [get_ports {ext_ram_data[5]}]
set_property PACKAGE_PIN V16 [get_ports {ext_ram_data[6]}]
set_property PACKAGE_PIN V17 [get_ports {ext_ram_data[7]}]
set_property PACKAGE_PIN V22 [get_ports {ext_ram_data[8]}]
set_property PACKAGE_PIN W25 [get_ports {ext_ram_data[9]}]
set_property PACKAGE_PIN V23 [get_ports {ext_ram_data[10]}]
set_property PACKAGE_PIN V21 [get_ports {ext_ram_data[11]}]
set_property PACKAGE_PIN U22 [get_ports {ext_ram_data[12]}]
set_property PACKAGE_PIN V26 [get_ports {ext_ram_data[13]}]
set_property PACKAGE_PIN U21 [get_ports {ext_ram_data[14]}]
set_property PACKAGE_PIN U25 [get_ports {ext_ram_data[15]}]
set_property PACKAGE_PIN AC24 [get_ports {ext_ram_data[16]}]
set_property PACKAGE_PIN AC26 [get_ports {ext_ram_data[17]}]
set_property PACKAGE_PIN AB25 [get_ports {ext_ram_data[18]}]
set_property PACKAGE_PIN AB24 [get_ports {ext_ram_data[19]}]
set_property PACKAGE_PIN AA22 [get_ports {ext_ram_data[20]}]
set_property PACKAGE_PIN AA24 [get_ports {ext_ram_data[21]}]
set_property PACKAGE_PIN AB26 [get_ports {ext_ram_data[22]}]
set_property PACKAGE_PIN AA23 [get_ports {ext_ram_data[23]}]
set_property PACKAGE_PIN R25 [get_ports {ext_ram_data[24]}]
set_property PACKAGE_PIN R23 [get_ports {ext_ram_data[25]}]
set_property PACKAGE_PIN R26 [get_ports {ext_ram_data[26]}]
set_property PACKAGE_PIN U20 [get_ports {ext_ram_data[27]}]
set_property PACKAGE_PIN T22 [get_ports {ext_ram_data[28]}]
set_property PACKAGE_PIN R22 [get_ports {ext_ram_data[29]}]
set_property PACKAGE_PIN T20 [get_ports {ext_ram_data[30]}]
set_property PACKAGE_PIN R14 [get_ports {ext_ram_data[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports ext_ram_ce_n]
set_property PACKAGE_PIN Y20 [get_ports ext_ram_ce_n]
set_property IOSTANDARD LVCMOS33 [get_ports ext_ram_oe_n]
set_property PACKAGE_PIN U24 [get_ports ext_ram_oe_n]
set_property IOSTANDARD LVCMOS33 [get_ports ext_ram_we_n]
set_property PACKAGE_PIN U16 [get_ports ext_ram_we_n]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_ctrl_ist/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {cpu_ist/mmu_ist/addr_i[0]} {cpu_ist/mmu_ist/addr_i[1]} {cpu_ist/mmu_ist/addr_i[2]} {cpu_ist/mmu_ist/addr_i[3]} {cpu_ist/mmu_ist/addr_i[4]} {cpu_ist/mmu_ist/addr_i[5]} {cpu_ist/mmu_ist/addr_i[6]} {cpu_ist/mmu_ist/addr_i[7]} {cpu_ist/mmu_ist/addr_i[8]} {cpu_ist/mmu_ist/addr_i[9]} {cpu_ist/mmu_ist/addr_i[10]} {cpu_ist/mmu_ist/addr_i[11]} {cpu_ist/mmu_ist/addr_i[12]} {cpu_ist/mmu_ist/addr_i[13]} {cpu_ist/mmu_ist/addr_i[14]} {cpu_ist/mmu_ist/addr_i[15]} {cpu_ist/mmu_ist/addr_i[16]} {cpu_ist/mmu_ist/addr_i[17]} {cpu_ist/mmu_ist/addr_i[18]} {cpu_ist/mmu_ist/addr_i[19]} {cpu_ist/mmu_ist/addr_i[20]} {cpu_ist/mmu_ist/addr_i[21]} {cpu_ist/mmu_ist/addr_i[22]} {cpu_ist/mmu_ist/addr_i[23]} {cpu_ist/mmu_ist/addr_i[24]} {cpu_ist/mmu_ist/addr_i[25]} {cpu_ist/mmu_ist/addr_i[26]} {cpu_ist/mmu_ist/addr_i[27]} {cpu_ist/mmu_ist/addr_i[28]} {cpu_ist/mmu_ist/addr_i[29]} {cpu_ist/mmu_ist/addr_i[30]} {cpu_ist/mmu_ist/addr_i[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 5 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {cpu_ist/datapath_ist/exceptCause_8c[0]} {cpu_ist/datapath_ist/exceptCause_8c[1]} {cpu_ist/datapath_ist/exceptCause_8c[2]} {cpu_ist/datapath_ist/exceptCause_8c[3]} {cpu_ist/datapath_ist/exceptCause_8c[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {cpu_ist/datapath_ist/instAddr_o[0]} {cpu_ist/datapath_ist/instAddr_o[1]} {cpu_ist/datapath_ist/instAddr_o[2]} {cpu_ist/datapath_ist/instAddr_o[3]} {cpu_ist/datapath_ist/instAddr_o[4]} {cpu_ist/datapath_ist/instAddr_o[5]} {cpu_ist/datapath_ist/instAddr_o[6]} {cpu_ist/datapath_ist/instAddr_o[7]} {cpu_ist/datapath_ist/instAddr_o[8]} {cpu_ist/datapath_ist/instAddr_o[9]} {cpu_ist/datapath_ist/instAddr_o[10]} {cpu_ist/datapath_ist/instAddr_o[11]} {cpu_ist/datapath_ist/instAddr_o[12]} {cpu_ist/datapath_ist/instAddr_o[13]} {cpu_ist/datapath_ist/instAddr_o[14]} {cpu_ist/datapath_ist/instAddr_o[15]} {cpu_ist/datapath_ist/instAddr_o[16]} {cpu_ist/datapath_ist/instAddr_o[17]} {cpu_ist/datapath_ist/instAddr_o[18]} {cpu_ist/datapath_ist/instAddr_o[19]} {cpu_ist/datapath_ist/instAddr_o[20]} {cpu_ist/datapath_ist/instAddr_o[21]} {cpu_ist/datapath_ist/instAddr_o[22]} {cpu_ist/datapath_ist/instAddr_o[23]} {cpu_ist/datapath_ist/instAddr_o[24]} {cpu_ist/datapath_ist/instAddr_o[25]} {cpu_ist/datapath_ist/instAddr_o[26]} {cpu_ist/datapath_ist/instAddr_o[27]} {cpu_ist/datapath_ist/instAddr_o[28]} {cpu_ist/datapath_ist/instAddr_o[29]} {cpu_ist/datapath_ist/instAddr_o[30]} {cpu_ist/datapath_ist/instAddr_o[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {cpu_ist/datapath_ist/instData_i[0]} {cpu_ist/datapath_ist/instData_i[1]} {cpu_ist/datapath_ist/instData_i[2]} {cpu_ist/datapath_ist/instData_i[3]} {cpu_ist/datapath_ist/instData_i[4]} {cpu_ist/datapath_ist/instData_i[5]} {cpu_ist/datapath_ist/instData_i[6]} {cpu_ist/datapath_ist/instData_i[7]} {cpu_ist/datapath_ist/instData_i[8]} {cpu_ist/datapath_ist/instData_i[9]} {cpu_ist/datapath_ist/instData_i[10]} {cpu_ist/datapath_ist/instData_i[11]} {cpu_ist/datapath_ist/instData_i[12]} {cpu_ist/datapath_ist/instData_i[13]} {cpu_ist/datapath_ist/instData_i[14]} {cpu_ist/datapath_ist/instData_i[15]} {cpu_ist/datapath_ist/instData_i[16]} {cpu_ist/datapath_ist/instData_i[17]} {cpu_ist/datapath_ist/instData_i[18]} {cpu_ist/datapath_ist/instData_i[19]} {cpu_ist/datapath_ist/instData_i[20]} {cpu_ist/datapath_ist/instData_i[21]} {cpu_ist/datapath_ist/instData_i[22]} {cpu_ist/datapath_ist/instData_i[23]} {cpu_ist/datapath_ist/instData_i[24]} {cpu_ist/datapath_ist/instData_i[25]} {cpu_ist/datapath_ist/instData_i[26]} {cpu_ist/datapath_ist/instData_i[27]} {cpu_ist/datapath_ist/instData_i[28]} {cpu_ist/datapath_ist/instData_i[29]} {cpu_ist/datapath_ist/instData_i[30]} {cpu_ist/datapath_ist/instData_i[31]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk25]
