-- DO NOT MODIFY THIS FILE.
-- This file is generated by hard_tests_gen

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.tne2_test_const.all;
use work.global_const.all;
use work.bus_const.all;

entity tne2_fake_ram is
    port (
        clk, rst: in std_logic;
        cpu_i: in BusC2D;
        cpu_o: out BusD2C
    );
end tne2_fake_ram;

architecture bhv of tne2_fake_ram is
    type WordsArray is array(0 to MAX_RAM_ADDRESS) of std_logic_vector(DataWidth);
    signal words: WordsArray;
    signal wordAddr: integer;
    signal bitSelect: std_logic_vector(DataWidth);
    signal llBit: std_logic;
    signal llLoc: std_logic_vector(AddrWidth);
begin
    cpu_o.busy <= PIPELINE_NONSTOP;

    wordAddr <= to_integer(unsigned(cpu_i.addr(11 downto 2)));

    bitSelect <= (
        31 downto 24 => cpu_i.byteSelect(3),
        23 downto 16 => cpu_i.byteSelect(2),
        15 downto 8 => cpu_i.byteSelect(1),
        7 downto 0 => cpu_i.byteSelect(0)
    );

    process (clk) begin
        if (rising_edge(clk)) then
            if (rst = RST_ENABLE) then
                -- CODE BELOW IS AUTOMATICALLY GENERATED
words(1) <= x"fe_ff_c6_34"; -- RUN ori $6, $6, 0xfffe
words(2) <= x"ee_ff_84_34"; -- RUN ori $4, $4, 0xffee
words(3) <= x"36_00_c4_00"; -- RUN tne $6, $4
words(4) <= x"0e_00_00_10"; -- RUN b 0x38
words(5) <= x"ff_ff_02_38"; -- RUN xori $2, $0, 0xffff
words(6) <= x"00_00_06_34"; -- RUN ori $6, $0, 0x0000
words(7) <= x"00_00_06_34"; -- RUN ori $6, $0, 0x0000
words(8) <= x"00_00_06_34"; -- RUN ori $6, $0, 0x0000
words(9) <= x"00_00_06_34"; -- RUN ori $6, $0, 0x0000
words(10) <= x"00_00_06_34"; -- RUN ori $6, $0, 0x0000
words(11) <= x"00_00_06_34"; -- RUN ori $6, $0, 0x0000
words(12) <= x"00_00_06_34"; -- RUN ori $6, $0, 0x0000
words(13) <= x"00_00_06_34"; -- RUN ori $6, $0, 0x0000
words(14) <= x"00_00_06_34"; -- RUN ori $6, $0, 0x0000
words(15) <= x"00_00_06_34"; -- RUN ori $6, $0, 0x0000
words(16) <= x"00_00_06_34"; -- RUN ori $6, $0, 0x0000
words(17) <= x"00_00_06_34"; -- RUN ori $6, $0, 0x0000
words(18) <= x"ff_00_06_34"; -- RUN ori $6, $0, 0x00ff
words(19) <= x"ff_ff_00_10"; -- RUN b -0x4
words(20) <= x"00_00_00_00"; -- RUN nop
            elsif ((cpu_i.enable = '1') and (cpu_i.write = '1')) then
                words(wordAddr) <= (words(wordAddr) and not bitSelect) or (cpu_i.dataSave and bitSelect);
            end if;
        end if;
    end process;

    cpu_o.dataLoad <= words(wordAddr) when (cpu_i.enable = '1') and (cpu_i.write = '0') else 32b"0";
end bhv;
