-- DO NOT MODIFY THIS FILE.
-- This file is generated by hard_tests_gen

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.tlb_tlbr_test_const.all;
use work.global_const.all;

entity tlb_tlbr_fake_ram is
    port (
        clk, rst: in std_logic;
        enable_i, write_i: in std_logic;
        data_i: in std_logic_vector(DataWidth);
        addr_i: in std_logic_vector(AddrWidth);
        byteSelect_i: in std_logic_vector(3 downto 0);
        data_o: out std_logic_vector(DataWidth)
    );
end tlb_tlbr_fake_ram;

architecture bhv of tlb_tlbr_fake_ram is
    type WordsArray is array(0 to MAX_RAM_ADDRESS) of std_logic_vector(DataWidth);
    signal words: WordsArray;
    signal wordAddr: integer;
    signal bitSelect: std_logic_vector(DataWidth);
begin
    wordAddr <= to_integer(unsigned(addr_i(31 downto 2)));

    bitSelect <= (
        31 downto 24 => byteSelect_i(3),
        23 downto 16 => byteSelect_i(2),
        15 downto 8 => byteSelect_i(1),
        7 downto 0 => byteSelect_i(0)
    );

    process (clk) begin
        if (rising_edge(clk)) then
            if (rst = RST_ENABLE) then
                -- CODE BELOW IS AUTOMATICALLY GENERATED
words(1) <= x"23_01_03_3c"; -- RUN lui $3, 0x0123
words(2) <= x"67_45_04_3c"; -- RUN lui $4, 0x4567
words(3) <= x"ab_89_05_3c"; -- RUN lui $5, 0x89ab
words(4) <= x"01_00_06_34"; -- RUN ori $6, $0, 0x1
words(5) <= x"00_50_83_40"; -- RUN mtc0 $3, $10
words(6) <= x"00_10_84_40"; -- RUN mtc0 $4, $2
words(7) <= x"00_18_85_40"; -- RUN mtc0 $5, $3
words(8) <= x"00_00_86_40"; -- RUN mtc0 $6, $0
words(9) <= x"00_00_00_00"; -- RUN nop
words(10) <= x"00_00_00_00"; -- RUN nop
words(11) <= x"02_00_00_42"; -- RUN tlbwi
words(12) <= x"11_11_03_3c"; -- RUN lui $3, 0x1111
words(13) <= x"22_22_04_3c"; -- RUN lui $4, 0x2222
words(14) <= x"33_33_05_3c"; -- RUN lui $5, 0x3333
words(15) <= x"02_00_06_34"; -- RUN ori $6, $0, 0x2
words(16) <= x"00_50_83_40"; -- RUN mtc0 $3, $10
words(17) <= x"00_10_84_40"; -- RUN mtc0 $4, $2
words(18) <= x"00_18_85_40"; -- RUN mtc0 $5, $3
words(19) <= x"00_00_86_40"; -- RUN mtc0 $6, $0
words(20) <= x"00_00_00_00"; -- RUN nop
words(21) <= x"00_00_00_00"; -- RUN nop
words(22) <= x"02_00_00_42"; -- RUN tlbwi
words(23) <= x"01_00_06_34"; -- RUN ori $6, $0, 0x1
words(24) <= x"00_00_86_40"; -- RUN mtc0 $6, $0
words(25) <= x"00_00_00_00"; -- RUN nop
words(26) <= x"00_00_00_00"; -- RUN nop
words(27) <= x"01_00_00_42"; -- RUN tlbr
words(28) <= x"00_00_00_00"; -- RUN nop
words(29) <= x"00_00_00_00"; -- RUN nop
words(30) <= x"00_00_00_00"; -- RUN nop
words(31) <= x"00_50_07_40"; -- RUN mfc0 $7, $10
words(32) <= x"00_10_08_40"; -- RUN mfc0 $8, $2
words(33) <= x"00_18_09_40"; -- RUN mfc0 $9, $3
            elsif ((enable_i = '1') and (write_i = '1')) then
                words(wordAddr) <= (words(wordAddr) and not bitSelect) or (data_i and bitSelect);
            end if;
        end if;
    end process;

    data_o <= words(wordAddr) when (enable_i = '1') and (write_i = '0') else 32b"0";
end bhv;
