-- DO NOT MODIFY THIS FILE.
-- This file is generated by hard_tests_gen

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.pushforwardcp1_test_const.all;
use work.global_const.all;
use work.bus_const.all;

entity pushforwardcp1_fake_ram is
    port (
        clk, rst: in std_logic;
        cpu_i: in BusC2D;
        cpu_o: out BusD2C
    );
end pushforwardcp1_fake_ram;

architecture bhv of pushforwardcp1_fake_ram is
    type WordsArray is array(0 to MAX_RAM_ADDRESS) of std_logic_vector(DataWidth);
    signal words: WordsArray;
    signal wordAddr: integer;
    signal bitSelect: std_logic_vector(DataWidth);
    signal llBit: std_logic;
    signal llLoc: std_logic_vector(AddrWidth);
begin
    cpu_o.busy <= PIPELINE_NONSTOP;

    wordAddr <= to_integer(unsigned(cpu_i.addr(11 downto 2)));

    bitSelect <= (
        31 downto 24 => cpu_i.byteSelect(3),
        23 downto 16 => cpu_i.byteSelect(2),
        15 downto 8 => cpu_i.byteSelect(1),
        7 downto 0 => cpu_i.byteSelect(0)
    );

    process (clk) begin
        if (rising_edge(clk)) then
            if (rst = RST_ENABLE) then
                -- CODE BELOW IS AUTOMATICALLY GENERATED
words(1) <= x"c3_ef_63_34"; -- RUN ori $3, $3, 0xefc3
words(2) <= x"00_10_83_44"; -- RUN mtc1 $3, $2
words(3) <= x"cd_ab_42_34"; -- RUN ori $2, $2, 0xabcd
words(4) <= x"00_10_04_44"; -- RUN mfc1 $4, $2
words(5) <= x"dc_8f_a5_34"; -- RUN ori $5, $5, 0x8fdc
words(6) <= x"00_10_c6_34"; -- RUN ori $6, $6, 0x1000
words(7) <= x"00_18_85_44"; -- RUN mtc1 $5, $3
words(8) <= x"00_18_06_44"; -- RUN mfc1 $6, $3
words(9) <= x"00_00_00_00"; -- RUN nop
words(10) <= x"00_00_00_00"; -- RUN nop
words(11) <= x"00_00_00_00"; -- RUN nop
words(12) <= x"00_00_00_00"; -- RUN nop
words(13) <= x"00_00_00_00"; -- RUN nop
            elsif ((cpu_i.enable = '1') and (cpu_i.write = '1')) then
                words(wordAddr) <= (words(wordAddr) and not bitSelect) or (cpu_i.dataSave and bitSelect);
            end if;
        end if;
    end process;

    cpu_o.dataLoad <= words(wordAddr) when (cpu_i.enable = '1') and (cpu_i.write = '0') else 32b"0";
end bhv;
