-- DO NOT MODIFY THIS FILE.
-- This file is generated by hard_tests_gen

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.branch_likely1_test_const.all;
use work.global_const.all;
use work.bus_const.all;

entity branch_likely1_fake_ram is
    port (
        clk, rst: in std_logic;
        cpu_i: in BusC2D;
        cpu_o: out BusD2C
    );
end branch_likely1_fake_ram;

architecture bhv of branch_likely1_fake_ram is
    type WordsArray is array(0 to MAX_RAM_ADDRESS) of std_logic_vector(DataWidth);
    signal words: WordsArray;
    signal wordAddr: integer;
    signal bitSelect: std_logic_vector(DataWidth);
    signal llBit: std_logic;
    signal llLoc: std_logic_vector(AddrWidth);
begin
    cpu_o.busy <= PIPELINE_NONSTOP;

    wordAddr <= to_integer(unsigned(cpu_i.addr(11 downto 2)));

    bitSelect <= (
        31 downto 24 => cpu_i.byteSelect(3),
        23 downto 16 => cpu_i.byteSelect(2),
        15 downto 8 => cpu_i.byteSelect(1),
        7 downto 0 => cpu_i.byteSelect(0)
    );

    process (clk) begin
        if (rising_edge(clk)) then
            if (rst = RST_ENABLE) then
                -- CODE BELOW IS AUTOMATICALLY GENERATED
words(1) <= x"04_00_42_34"; -- RUN ori $2, $2, 0x4
words(2) <= x"08_00_42_20"; -- RUN addi $2, $2, 0x8
words(3) <= x"26_18_63_00"; -- RUN xor $3, $3, $3
words(4) <= x"03_00_84_34"; -- RUN ori $4, 0x03
words(5) <= x"02_00_42_20"; -- RUN addi $2, $2, 0x2
words(6) <= x"01_00_63_20"; -- RUN addi $3, $3, 0x1
words(7) <= x"fd_ff_64_54"; -- RUN bnel $3, $4, -0xc
words(8) <= x"00_01_42_20"; -- RUN addi $2, $2, 0x100
            elsif ((cpu_i.enable = '1') and (cpu_i.write = '1')) then
                words(wordAddr) <= (words(wordAddr) and not bitSelect) or (cpu_i.dataSave and bitSelect);
            end if;
        end if;
    end process;

    cpu_o.dataLoad <= words(wordAddr) when (cpu_i.enable = '1') and (cpu_i.write = '0') else 32b"0";
end bhv;
